---
name: Bug Report
description: File a bug report
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this security report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: security-issue
    attributes:
      label: Describe the security issue ?
      description: Please describe the issue
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: Please write the steps in a list form. Don't hesitate to upload reports file (https://www.swisstransfer.com/en-us) and paste the link
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: How serious the vunlerability is ?
      description: Evaluate the severity of the vulnerability (Low, Med, High)
      multiple: false
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Optional Screenshots
      description: Add any relevant screenshots.
      placeholder: Drag and drop your screenshots here, if any.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output, if any. This will be automatically formatted into code, so no need for backticks.
      render: Shell
